name: Docker Build and Push

on:
  push:
    paths:
      - "Dockerfile"
      - "nginx.template.conf"
      - ".github/workflows/deploy_to_dockerhub.yml"
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get current date
        id: current_date
        run: |
          echo "current_date=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/nginx-http3-br:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/nginx-http3-br:${{ env.current_date }}